[tool.poetry]
name = "bionic"
version = "0.1.0"
description = "Basically Irreplaceable Oxygen Not Included Calculator"
authors = ["Pendragonek <mateuszlekner@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
kivy = "^2.3.0"
pydantic = "^2.7.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
black = "^24.4.2"
isort = "^5.13.2"
pylint = "^3.1.0"
mypy = "^1.10.0"

[tool.pylint.base]
max-line-length = 88
extension-pkg-allow-list = ["pydantic"]

[tool.isort]
profile = 'black'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bionic = "bionic.__main__:main"